require_relative './mls_standings_cli_app/version'
require_relative './mls_standings_cli_app/team'
require_relative './mls_standings_cli_app/cli'
require_relative './mls_standings_cli_app/scraper'
require_relative '../config/environment'
